[package]
name = "rustc_apfloat"
version = "0.0.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "decimal"
harness = false
